import React from 'react';
import { Language } from '../types';

interface FooterProps {
  language: Language;
}

const Footer: React.FC<FooterProps> = ({ language }) => {
  return (
    <footer className="py-8 mt-12 border-t border-slate-800 text-center">
      <p className="text-slate-500 text-sm">
        {language === 'zh' 
          ? '由 Gemini 2.5 驱动 • 聚焦 AI 与机器人行业'
          : 'Powered by Gemini 2.5 • Focus on AI & Robotics Industry'
        }
      </p>
      <p className="text-slate-600 text-xs mt-2">
        {language === 'zh'
          ? '数据由 AI 生成，仅供演示。'
          : 'Data is generated by AI for demonstration purposes.'
        }
      </p>
    </footer>
  );
};

export default Footer;